# Generated by Django 5.1 on 2024-08-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='generomodel',
            table='generos',
        ),
        migrations.AlterModelTable(
            name='librosmodel',
            table='libros',
        ),
    ]
